use_frameworks!

platform :ios, '8.0'

target 'WXWCategory_Example' do
  pod 'WXWCategory', :path => '../'

  target 'WXWCategory_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
